### ISSUE TITLE
Save Photo To Album - Android (not tested on iOS)

### ISSUE THREAD

**Issue by accttech** [apache/cordova-plugin-camera#341]
When I use `saveToPhotoAlbum:  true;` it throws "Unable to obtain picture: Error capturing image.". When im not using `saveToPhotoAlbum`, it saves the picture to the cache, and removes it after a few days. I need the picture to be persistent.

**Comment by janpio** [comment]
Then open a new issue @HarelM instead of posting to this unrelated issue. Thanks.

**Comment by HarelM** [comment]
Sure thing.

**Comment by timbru31** [comment]
Is this issue still relevant? Is this reproducible in a new, plain Cordova app? A minimal reproduction repository would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

**Comment by PieterVanPoyer** [comment]
Issue still seems to be present.
Using the camera with the saveToPhotoAlbum true fails.

Reproduction is available at https://github.com/PieterVanPoyer/cordova-camera-plugin-testing-app/tree/master

This is the stacktrace of an Android 7 (Nexus 6) emulator.

```
2020-09-28 10:37:21.298 9599-9599/com.pvpoyer.cameraplugintesting D/CordovaInterfaceImpl: Sending activity result to plugin
2020-09-28 10:37:21.298 9599-9599/com.pvpoyer.cameraplugintesting I/ExifInterface_JNI: Raw image not detected
2020-09-28 10:37:21.304 9599-9599/com.pvpoyer.cameraplugintesting W/System.err: java.io.FileNotFoundException: content:/com.pvpoyer.cameraplugintesting.cordova.plugin.camera.provider/cache_files/.Pic.jpg (No such file or directory)
2020-09-28 10:37:21.304 9599-9599/com.pvpoyer.cameraplugintesting W/System.err:     at java.io.FileInputStream.open(Native Method)
2020-09-28 10:37:21.304 9599-9599/com.pvpoyer.cameraplugintesting W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:146)
2020-09-28 10:37:21.304 9599-9599/com.pvpoyer.cameraplugintesting W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:99)
2020-09-28 10:37:21.304 9599-9599/com.pvpoyer.cameraplugintesting W/System.err:     at org.apache.cordova.camera.CameraLauncher.writeUncompressedImage(CameraLauncher.java:903)
2020-09-28 10:37:21.304 9599-9599/com.pvpoyer.cameraplugintesting W/System.err:     at org.apache.cordova.camera.CameraLauncher.processResultFromCamera(CameraLauncher.java:503)
2020-09-28 10:37:21.304 9599-9599/com.pvpoyer.cameraplugintesting W/System.err:     at org.apache.cordova.camera.CameraLauncher.onActivityResult(CameraLauncher.java:808)
2020-09-28 10:37:21.304 9599-9599/com.pvpoyer.cameraplugintesting W/System.err:     at org.apache.cordova.CordovaInterfaceImpl.onActivityResult(CordovaInterfaceImpl.java:159)
2020-09-28 10:37:21.304 9599-9599/com.pvpoyer.cameraplugintesting W/System.err:     at org.apache.cordova.CordovaActivity.onActivityResult(CordovaActivity.java:361)
2020-09-28 10:37:21.304 9599-9599/com.pvpoyer.cameraplugintesting W/System.err:     at android.app.Activity.dispatchActivityResult(Activity.java:6932)
2020-09-28 10:37:21.304 9599-9599/com.pvpoyer.cameraplugintesting W/System.err:     at android.app.ActivityThread.deliverResults(ActivityThread.java:4085)
2020-09-28 10:37:21.304 9599-9599/com.pvpoyer.cameraplugintesting W/System.err:     at android.app.ActivityThread.handleSendResult(ActivityThread.java:4132)
2020-09-28 10:37:21.304 9599-9599/com.pvpoyer.cameraplugintesting W/System.err:     at android.app.ActivityThread.-wrap20(ActivityThread.java)
2020-09-28 10:37:21.305 9599-9599/com.pvpoyer.cameraplugintesting W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1533)
2020-09-28 10:37:21.305 9599-9599/com.pvpoyer.cameraplugintesting W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
2020-09-28 10:37:21.305 9599-9599/com.pvpoyer.cameraplugintesting W/System.err:     at android.os.Looper.loop(Looper.java:154)
2020-09-28 10:37:21.305 9599-9599/com.pvpoyer.cameraplugintesting W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6119)
2020-09-28 10:37:21.305 9599-9599/com.pvpoyer.cameraplugintesting W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-09-28 10:37:21.305 9599-9599/com.pvpoyer.cameraplugintesting W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
2020-09-28 10:37:21.305 9599-9599/com.pvpoyer.cameraplugintesting W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
2020-09-28 10:37:21.307 9599-9599/com.pvpoyer.cameraplugintesting D/CordovaActivity: Started the activity.
2020-09-28 10:37:21.307 9599-9599/com.pvpoyer.cameraplugintesting D/CordovaActivity: Resumed the activity.
2020-09-28 10:37:21.308 9599-9599/com.pvpoyer.cameraplugintesting I/chromium: [INFO:CONSOLE(77)] "Unable to obtain picture: Error capturing image.", source: file:///android_asset/www/js/index.js (77)
```
