### ISSUE TITLE
Unable to add cordova-plugin-camera with Phonegap 8.0

### ISSUE THREAD

**Issue by FreddyCrugger** [apache/cordova-plugin-camera#355]
Hello,

phonegap 8.0
android 7.1.1

I am trying to add the camera plugin but keep getting this error:

```
PS C:\laragon\www\keep> phonegap plugin add cordova-plugin-camera
No scripts found for hook "before_plugin_add".


No version specified for cordova-plugin-camera, retrieving version from package.json


Calling plugman.fetch on plugin "cordova-plugin-camera@^4.0.3"

Calling plugman.install on plugin "C:\laragon\www\keep\plugins\cordova-plugin-camera" for platform "android


Installing "cordova-plugin-camera" for android

Running command: cmd "/s /c "C:\laragon\www\keep\platforms\android\cordova\version.bat""


Command finished with error code 0: cmd /s /c "C:\laragon\www\keep\platforms\android\cordova\version.bat"


Finding scripts for "before_plugin_install" hook from plugin cordova-plugin-camera on android platform only.

No scripts found for hook "before_plugin_install".

Install start for "cordova-plugin-camera" on android.

PlatformApi successfully found for platform android


Android Studio project detected


Beginning processing of action stack for android project...


Error during processing of action! Attempting to revert...


Failed to install 'cordova-plugin-camera': CordovaError: Uh oh!
"C:\laragon\www\keep\platforms\android\app\src\main\res\xml\camera_provider_paths.xml" already exists!
    at copyNewFile (C:\laragon\www\keep\platforms\android\cordova\lib\pluginHandlers.js:261:45)
    at install (C:\laragon\www\keep\platforms\android\cordova\lib\pluginHandlers.js:51:17)
    at ActionStack.process (C:\laragon\www\keep\platforms\android\cordova\node_modules\cordova-common\src\ActionStack.js:56:25)
    at PluginManager.doOperation (C:\laragon\www\keep\platforms\android\cordova\node_modules\cordova-common\src\PluginManager.js:114:20)
    at PluginManager.addPlugin (C:\laragon\www\keep\platforms\android\cordova\node_modules\cordova-common\src\PluginManager.js:144:17)
    at C:\laragon\www\keep\platforms\android\cordova\Api.js:247:74
    at _fulfilled (C:\laragon\www\keep\platforms\android\cordova\node_modules\q\q.js:854:54)
    at self.promiseDispatch.done (C:\laragon\www\keep\platforms\android\cordova\node_modules\q\q.js:883:30)
    at Promise.promise.promiseDispatch (C:\laragon\www\keep\platforms\android\cordova\node_modules\q\q.js:816:13)
    at C:\laragon\www\keep\platforms\android\cordova\node_modules\q\q.js:570:49


(node:6980) UnhandledPromiseRejectionWarning: CordovaError: Uh oh!
"C:\laragon\www\keep\platforms\android\app\src\main\res\xml\camera_provider_paths.xml" already exists!
    at copyNewFile (C:\laragon\www\keep\platforms\android\cordova\lib\pluginHandlers.js:261:45)
    at install (C:\laragon\www\keep\platforms\android\cordova\lib\pluginHandlers.js:51:17)
    at ActionStack.process (C:\laragon\www\keep\platforms\android\cordova\node_modules\cordova-common\src\ActionStack.js:56:25)
    at PluginManager.doOperation (C:\laragon\www\keep\platforms\android\cordova\node_modules\cordova-common\src\PluginManager.js:114:20)
    at PluginManager.addPlugin (C:\laragon\www\keep\platforms\android\cordova\node_modules\cordova-common\src\PluginManager.js:144:17)
    at C:\laragon\www\keep\platforms\android\cordova\Api.js:247:74
    at _fulfilled (C:\laragon\www\keep\platforms\android\cordova\node_modules\q\q.js:854:54)
    at self.promiseDispatch.done (C:\laragon\www\keep\platforms\android\cordova\node_modules\q\q.js:883:30)
    at Promise.promise.promiseDispatch (C:\laragon\www\keep\platforms\android\cordova\node_modules\q\q.js:816:13)
    at C:\laragon\www\keep\platforms\android\cordova\node_modules\q\q.js:570:49

(node:6980) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6980) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled
will terminate the Node.js process with a non-zero exit code.
```

Any idea why please?

Thank you.

**Comment by jcesarmobile** [comment]
remove the android platform and add it again, looks like it's in an inconsistent state and some files are already there

**Comment by FreddyCrugger** [comment]
Thanks
