### ISSUE TITLE
App crashs in Android 8.1.0

### ISSUE THREAD

**Issue by desmeit** [apache/cordova-plugin-camera#406]
The camera plugin is working with Android 7.0 but not with a Samsung J9 2017 and Android 8.1.0. After calling Camera Plugin it crashs the App:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.intervall_fasten.app, PID: 27814
    android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=null pri=-2 contentView=null vibrate=null sound=null defaults=0x0 flags=0x42 color=0x00000000 number=0 vis=PRIVATE semFlags=0x0 semPriority=0 semMissedCount=0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1906)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:7000)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
Application terminated.
```

I use the following code:

```
	function onSuccess(imageURI) {   
															
									if (device.platform.toLowerCase() == 'android'){												  
								  		cordova.plugins.backgroundMode.disable();  
									}
						//
								
									})
						
															
							 }                                                                                           
																														
							 function onFail(message) {                                                                  
								  console.log('Failed because: ' + message);                                                    
							 }  

 if(typeof navigator !== 'undefined' && typeof navigator.camera !== 'undefined') {           
								  console.log('calling getPicture');                                                            
								  navigator.camera.getPicture(onSuccess, onFail, { 
								  	   quality: 80,    
									   correctOrientation: true,                                   
									   sourceType: Camera.PictureSourceType.CAMERA,                                  
									   destinationType: Camera.DestinationType.FILE_URI                             
								  });                                                                                     
							 } else {                                                                                    
								  console.log('no navigator.camera - did you install the plugin?');                                                           
							 }  
```

**Comment by omazim** [comment]
> Ditching the 'quality' option when capturing from Camera helped me.

Can you show the options you applied? I tried ditching the 'quality' option but it didn't help.

**Comment by kklindic** [comment]
Ditching the 'quality' option helped me also on Android 9.
I also got app crashing when trying to call getPictures() method without any options.

**Comment by girigiramesh** [comment]
Need to add the NotificationChannel for above Android Oreo versions.

**Comment by timlut** [comment]
@girigiramesh can you show whtat you mean with "Need to add the NotificationChannel for above Android Oreo versions."

Thanks!

**Comment by girigiramesh** [comment]
@timlut In Android, up to Android Nougat, there is no need of NotificationChannel for startForeground. From Android Oreo onwards we need to add the NotificationChannel for startForeground.

**Comment by daveshirman** [comment]
Has anyone found a solution to this? I tried commenting out the quality option, but it still crashes.
Thanks

**Comment by jcesarmobile** [comment]
I can’t reproduce and the plugin is not calling startForeground, so it’s probably a bug in another plugin you are using.
