### ISSUE TITLE
Tests fail on local (non-SauceLabs) iOS 10

### ISSUE THREAD

**Issue by janpio** [apache/cordova-plugin-camera#464]
https://travis-ci.org/apache/cordova-plugin-camera/jobs/547251022

```
Start running Appium tests...
Running Appium tests locally
paramedic-appium: Found tests in: /var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/tmp-27081LTu7isuAwuB/plugins/cordova-plugin-camera/appium-tests/ios
paramedic-appium: Setting "CameraUsesGeolocation" preference to "true"
paramedic-appium: Adding CSP source "http://*" to directive "connect-src"
paramedic-appium: Adding a whitelist "access" rule for origin: *
paramedic-appium: It is already in place
/private/var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/tmp-27081LTu7isuAwuB /private/var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/tmp-27081LTu7isuAwuB /Users/travis/build/apache/cordova-plugin-camera
$ cordova plugin add cordova-save-image-gallery --no-telemetry --no-update-notifier
Installing "cordova-save-image-gallery" for ios
Adding cordova-save-image-gallery to package.json
/private/var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/tmp-27081LTu7isuAwuB /Users/travis/build/apache/cordova-plugin-camera
paramedic-appium: Building the app...
$ cordova build ios --no-telemetry --no-update-notifier
ls: no such file or directory: /var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/tmp-27081LTu7isuAwuB/platforms/ios/build/emulator*.app
paramedic-appium: Looking for the app package in: /var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/tmp-27081LTu7isuAwuB/platforms/ios/build/emulator
/Users/travis/.nvm/versions/node/v6.17.1/lib/node_modules/cordova-paramedic/lib/appium/AppiumRunner.js:370
        throw new Error('Could not find the app package');
        ^
Error: Could not find the app package
    at getPackagePath (/Users/travis/.nvm/versions/node/v6.17.1/lib/node_modules/cordova-paramedic/lib/appium/AppiumRunner.js:370:15)
    at child_process.exec (/Users/travis/.nvm/versions/node/v6.17.1/lib/node_modules/cordova-paramedic/lib/appium/AppiumRunner.js:291:43)
    at ChildProcess.exithandler (child_process.js:190:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
The command "if [[ "$ADDITIONAL_TESTS_DIR" != "" ]]; then cd $ADDITIONAL_TESTS_DIR && npm install && npm test; else $PARAMEDIC_COMMAND --config ./pr/$PLATFORM --plugin $PARAMEDIC_PLUGIN_TO_TEST --buildName $PARAMEDIC_BUILDNAME; fi" exited with 1.
```

The app was actually launched via that folder before:
`/private/var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/tmp-27081LTu7isuAwuB/platforms/ios/build/emulator/HelloCordova.app`

**Comment by janpio** [comment]
Bug was introduced to paramedic here:
https://github.com/apache/cordova-paramedic/commit/bd8f0bbc1447fe3d3a9c50a5134970ec534c9c0d#diff-4eee9abd155785076b018599e5f1d76cR359

This is now missing a `/` between the path and mask.

**Comment by janpio** [comment]
Fixed in paramedic. New problem with install of appium. 
Test fix via https://github.com/apache/cordova-plugin-camera/pull/455/commits/70cb5a8bad4941018ea4edba6b63886ef1a45a03

**Comment by janpio** [comment]
"Success" - now it fails with the same error message as all the other iOS Appium tests: https://github.com/apache/cordova-plugin-camera/issues/465
