### ISSUE TITLE
Can't get picture from downloads folder on Android 9

### ISSUE THREAD

**Issue by AndrWeisR** [apache/cordova-plugin-camera#531]
# Bug Report

## Problem
I'm using camera.getPicture to open an existing image on the device, in Android 9. I can select images in the gallery OK, but selecting images in the download folder throws an error and returns null for the image. Note on Android 8, opening images from the Downloads folder works.

### What is expected to happen?
An image in the Downloads folder should be selectable on Android 9, the same as Android 8.

### What does actually happen?

You get the following errors when you select an image in the Downloads folder, and null is returned for the image data:

```
2019-11-25 13:44:52.088 4241-4241/com.android.documentsui D/PickerActionHandler: onFinished() [content://com.android.providers.downloads.documents/document/25]
2019-11-25 13:44:52.099 3272-3272/com.app.myapp D/CordovaActivity: Incoming Result. Request code = 18
2019-11-25 13:44:52.099 3272-3272/com.app.myapp D/CordovaInterfaceImpl: Sending activity result to plugin
2019-11-25 13:44:52.101 3272-3272/com.app.myapp D/CordovaActivity: Started the activity.
2019-11-25 13:44:52.102 3272-3272/com.app.myapp D/CordovaActivity: Resumed the activity.
2019-11-25 13:44:52.109 2604-2645/android.process.media E/DatabaseUtils: Writing exception to parcel
    java.lang.IllegalArgumentException: Unknown URI: content://downloads/public_downloads/25
        at com.android.providers.downloads.DownloadProvider.query(DownloadProvider.java:933)
        at android.content.ContentProvider.query(ContentProvider.java:1055)
        at android.content.ContentProvider.query(ContentProvider.java:1147)
        at android.content.ContentProvider$Transport.query(ContentProvider.java:240)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:102)
        at android.os.Binder.execTransact(Binder.java:731)
2019-11-25 13:44:52.110 3272-4568/com.app.myapp D/CameraLauncher: File location is: null
```

## Information

Fails with all PictureSourceTypes and DestinationTypes.

I think the **root cause** is at line 106 of FileHelper.java:

```
 final Uri contentUri = ContentUris.withAppendedId(
                                Uri.parse("content://downloads/public_downloads"), Long.valueOf(id));
```

In Android 9, my downloaded files (downloaded from Chrome) are in "all_downloads", not "public_downloads".

### Command or Code

```
    const options: CameraOptions = {
      mediaType: this.camera.MediaType.PICTURE,
      correctOrientation: true,
      targetWidth: 1024,
      sourceType: this.camera.PictureSourceType.PHOTOLIBRARY,
      destinationType: this.camera.DestinationType.FILE_URI
    };

    this.camera.getPicture(options).then((imageData) => {
```

### Environment, Platform, Device

Android 9

### Version information

Ionic 4.11.2
Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
Cordova Platforms : android 8.1.0
Android 9

## Checklist

- [ x] I searched for existing GitHub issues
- [ x] I updated all Cordova tooling to most recent version
- [ x] I included all the necessary information above

**Comment by mirko77** [comment]
No problems on

Android 9
cordova-android 7.1.4
cordova cli 8.1.2

**Comment by jorgearmandooc** [comment]
Same problem but with videos, selecting video from downloads folder returns null:

os: android: 8.0.0
cordova: 9.0.0 (cordova-lib@9.0.1)
cordova-android: 8.1.0
cordova-plugin-camera : 4.1.0

			```
destinationType: Camera.DestinationType.FILE_URI,
			sourceType: Camera.PictureSourceType.PHOTOLIBRARY,
			mediaType:Camera.MediaType.ALLMEDIA,
			targetWidth:700,
			targetHeight:700,
			quality:40,
			correctOrientation: true
```

**Comment by jorgearmandooc** [comment]
I maked some tests and i discover that if you open the Downloads folder an select a video then fails and return null.

But if you first goes to the Videos folder and after select Downloads into videos folder works well.
