### ISSUE TITLE
Windows 10: Camera Plugin does not work

### ISSUE THREAD

**Issue by srinidhirao** [apache/cordova-plugin-camera#542]
### Issue Type

- [x] Bug Report
- [ ] Feature Request
- [ ] Support Question

## Description

Using the camera plugin fails with an error. We are building an Ionic 4 app targeting Windows 10 platform. 

### Command or Code

````
Exception was thrown at line 81605, column 56 in ms-appx-web://io.ionic.starter/www/build/vendor.js
0x800a138a - JavaScript runtime error: Function expected
Exception was thrown at line 15744, column 9 in ms-appx-web://io.ionic.starter/www/build/vendor.js
0x800a138a - JavaScript runtime error: Function expected
Exception was thrown at line 3, column 19746 in ms-appx-web://io.ionic.starter/www/build/polyfills.js
0x800a139e - JavaScript runtime error: Uncaught (in promise): TypeError: Function expected
TypeError: Function expected
   at Camera.prototype.getPicture (ms-appx-web://io.ionic.starter/www/build/vendor.js:81605:56)
   at ContactPage (ms-appx-web://io.ionic.starter/www/build/main.js:146:9)
   at createClass (ms-appx-web://io.ionic.starter/www/build/vendor.js:13119:13)
   at createDirectiveInstance (ms-appx-web://io.ionic.starter/www/build/vendor.js:12962:5)
   at createViewNodes (ms-appx-web://io.ionic.starter/www/build/vendor.js:14420:21)
   at createRootView (ms-appx-web://io.ionic.starter/www/build/vendor.js:14309:5)
   at callWithDebugContext (ms-appx-web://io.ionic.starter/www/build/vendor.js:15734:9)
   at debugCreateRootView (ms-appx-web://io.ionic.starter/www/build/vendor.js:15017:5)
   at ComponentFactory_.prototype.create (ms-appx-web://io.ionic.starter/www/build/vendor.js:11914:9)
   at ComponentFactoryBoundToModule.prototype.create (ms-appx-web://io.ionic.starter/www/build/vendor.js:4666:9)
````

### Environment, Platform, Device

````
C:\Users\VPNUser\Documents\MyIonicProject>ionic info

Ionic:

   ionic (Ionic CLI)  : 4.5.0 (C:\Users\VPNUser\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.9
   @ionic/app-scripts : 3.2.4

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : windows 6.0.1
   Cordova Plugins       : not available

System:

   NodeJS : v12.14.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.13.4
   OS     : Windows 10

````

## Checklist

- [x] I searched for already existing GitHub issues about this
- [x] I updated all Cordova tooling to their most recent version
- [x] I included all the necessary information above

**Comment by erisu** [comment]
[Cordova Windows](https://github.com/apache/cordova-windows) has been deprecated and is no longer supported making this issue obsolete.
