### ISSUE TITLE
RecoverableSecurityException when trying to delete the picture from the MediaStore

### ISSUE THREAD

**Issue by Balgam** [apache/cordova-plugin-camera#656]
# Bug Report

RecoverableSecurityException when trying to delete the image from the MediaStore during the cleanup process.

### What is expected to happen?

During the cleanup process, the image should be deleted from the MediaStore and file system.

### What does actually happen?

A RecoverableSecurityException occurs when try to delete the image from MediaStore.

```
android.app.RecoverableSecurityException: com.xxx.xxx has no access to content://media/external/images/media/529
  at android.app.RecoverableSecurityException$1.createFromParcel(RecoverableSecurityException.java:197)
  at android.app.RecoverableSecurityException$1.createFromParcel(RecoverableSecurityException.java:194)
  at android.os.Parcel.readParcelable(Parcel.java:2973)
  at android.os.Parcel.createException(Parcel.java:2066)
  at android.os.Parcel.readException(Parcel.java:2039)
  at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:188)
  at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
  at android.content.ContentProviderProxy.delete(ContentProviderNative.java:553)
  at android.content.ContentResolver.delete(ContentResolver.java:1952)
  at org.apache.cordova.camera.CameraLauncher.checkForDuplicateImage(CameraLauncher.java:1314)
  at org.apache.cordova.camera.CameraLauncher.cleanup(CameraLauncher.java:1213)
  at org.apache.cordova.camera.CameraLauncher.processResultFromCamera(CameraLauncher.java:605)
  at org.apache.cordova.camera.CameraLauncher.onActivityResult(CameraLauncher.java:817)
  at org.apache.cordova.CordovaInterfaceImpl.onActivityResult(CordovaInterfaceImpl.java:159)
  at org.apache.cordova.CordovaActivity.onActivityResult(CordovaActivity.java:361)
  at android.app.Activity.dispatchActivityResult(Activity.java:8301)
  at android.app.ActivityThread.deliverResults(ActivityThread.java:4839)
  at android.app.ActivityThread.handleSendResult(ActivityThread.java:4887)
  at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
  at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2017)
  at android.os.Handler.dispatchMessage(Handler.java:107)
  at android.os.Looper.loop(Looper.java:214)
  at android.app.ActivityThread.main(ActivityThread.java:7397)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
```

### Command or Code
```
Uri uri = Uri.parse(contentStore + "/" + id);
this.cordova.getActivity().getContentResolver().delete(uri, null, null);
```

### Environment, Platform, Device
```
Android 10
<uses-sdk android:minSdkVersion="22" android:targetSdkVersion="29" />
```

### Version information

```
Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
Cordova Platforms : android 9.0.0
Cordova Plugins   : cordova-plugin-camera 4.1.0, cordova-plugin-camera 4.2.0, cordova-plugin-camera 5.0.0-dev 
```

## Checklist

- [X] I searched for existing GitHub issues
- [X] I updated all Cordova tooling to most recent version
- [X] I included all the necessary information above

**Comment by AshishPro04** [comment]
> # Bug Report
> RecoverableSecurityException when trying to delete the image from the MediaStore during the cleanup process.
> 
> ### What is expected to happen?
> During the cleanup process, the image should be deleted from the MediaStore and file system.
> 
> ### What does actually happen?
> A RecoverableSecurityException occurs when try to delete the image from MediaStore.
> 
> ```
> android.app.RecoverableSecurityException: com.xxx.xxx has no access to content://media/external/images/media/529
>   at android.app.RecoverableSecurityException$1.createFromParcel(RecoverableSecurityException.java:197)
>   at android.app.RecoverableSecurityException$1.createFromParcel(RecoverableSecurityException.java:194)
>   at android.os.Parcel.readParcelable(Parcel.java:2973)
>   at android.os.Parcel.createException(Parcel.java:2066)
>   at android.os.Parcel.readException(Parcel.java:2039)
>   at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:188)
>   at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
>   at android.content.ContentProviderProxy.delete(ContentProviderNative.java:553)
>   at android.content.ContentResolver.delete(ContentResolver.java:1952)
>   at org.apache.cordova.camera.CameraLauncher.checkForDuplicateImage(CameraLauncher.java:1314)
>   at org.apache.cordova.camera.CameraLauncher.cleanup(CameraLauncher.java:1213)
>   at org.apache.cordova.camera.CameraLauncher.processResultFromCamera(CameraLauncher.java:605)
>   at org.apache.cordova.camera.CameraLauncher.onActivityResult(CameraLauncher.java:817)
>   at org.apache.cordova.CordovaInterfaceImpl.onActivityResult(CordovaInterfaceImpl.java:159)
>   at org.apache.cordova.CordovaActivity.onActivityResult(CordovaActivity.java:361)
>   at android.app.Activity.dispatchActivityResult(Activity.java:8301)
>   at android.app.ActivityThread.deliverResults(ActivityThread.java:4839)
>   at android.app.ActivityThread.handleSendResult(ActivityThread.java:4887)
>   at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
>   at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
>   at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
>   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2017)
>   at android.os.Handler.dispatchMessage(Handler.java:107)
>   at android.os.Looper.loop(Looper.java:214)
>   at android.app.ActivityThread.main(ActivityThread.java:7397)
>   at java.lang.reflect.Method.invoke(Native Method)
>   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
>   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
> ```
> 
> ## Information
> ### Command or Code
> ```
> Uri uri = Uri.parse(contentStore + "/" + id);
> this.cordova.getActivity().getContentResolver().delete(uri, null, null);
> ```
> 
> ### Environment, Platform, Device
> ```
> Android 10
> <uses-sdk android:minSdkVersion="22" android:targetSdkVersion="29" />
> ```
> 
> ### Version information
> ```
> Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
> Cordova Platforms : android 9.0.0
> Cordova Plugins   : cordova-plugin-camera 4.1.0, cordova-plugin-camera 4.2.0, cordova-plugin-camera 5.0.0-dev 
> ```
> 
> ## Checklist
> * [x]  I searched for existing GitHub issues
> * [x]  I updated all Cordova tooling to most recent version
> * [x]  I included all the necessary information above

**Comment by AshishPro04** [comment]
Hi did you solved the issue? 
I'm having the same issue here.

**Comment by Balgam** [comment]
> Hi did you solved the issue?
> I'm having the same issue here.

Hi,
I'm currently using cordova 10.0.0 with android platform 9.0.0 and camera plugin 5.0.1-dev. 
This combination seems to work for now with targetSdk 29.

**Comment by PieterVanPoyer** [comment]
https://github.com/apache/cordova-plugin-camera/issues/679 and this one are duplicates.

Although this issue is older (with a nice stacktrace), I keep https://github.com/apache/cordova-plugin-camera/issues/679 open.

**Comment by pravindesai** [comment]
have you solved this isuue ?

**Comment by TheMartas29** [comment]
this issue is solved in new version of the plugin, the difference is in this commit: https://github.com/ibcomputing/cordova-plugin-camera/commit/2340e09344cbea4cb9b8e0d301d99a5824f48e21
